### ISSUE TITLE
Typos in snippets.json

### ISSUE THREAD

**Issue by chplusink** [mateuspv/shopify-schema-settings-snippets#1]
The color type schema has a few typos:

- Line 34: `Schama` > `Schema`
- Line 36: Missing colons after `type` and `info`

**Comment by mateuspv** [comment]
Thanks, already merged your pr.

I've unpublish the package, since I'm using this one:
https://marketplace.visualstudio.com/items?itemName=killalau.vscode-liquid-snippets

I found it more complete, and there's no reason to keep this one published.

If you still want to use it, you can copy the snippets and paste on your personal snippets.
https://code.visualstudio.com/docs/editor/userdefinedsnippets

Best
